parameters:
    gasPriceUrl: "%env(GAS_PRICE_URL)%"
    gasPricePath: "%env(GAS_PRICE_PATH)%"
    gasPriceName: "%env(GAS_PRICE_NAME)%"
    gasPriceJsonName: "%env(GAS_PRICE_JSON_NAME)%"
    positionStackApiKey: "%env(POSITION_STACK_API_KEY)%"
    positionStackUrl: "%env(POSITION_STACK_URL)%"
    googleApiKey: "%env(GOOGLE_API_KEY)%"
    placeTextsearchUrl: "%env(PLACE_TEXTSEARCH_URL)%"
    placeDetailsUrl: "%env(PLACE_DETAILS_URL)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $gasPriceUrl: "%gasPriceUrl%"
            string $gasPricePath: "%gasPricePath%"
            string $gasPriceName: "%gasPriceName%"
            string $gasPriceJsonName: "%gasPriceJsonName%"
            string $positionStackApiKey: "%positionStackApiKey%"
            string $positionStackUrl: "%positionStackUrl%"
            string $googleApiKey: "%googleApiKey%"
            string $placeTextsearchUrl: "%placeTextsearchUrl%"
            string $placeDetailsUrl: "%placeDetailsUrl%"

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\ApiResource\Controller\:
        resource: "../src/ApiResource/Controller/"
        tags: ["controller.service_arguments"]

    App\Decorator\JwtDecorator:
        decorates: "api_platform.openapi.factory"

    App\Subscriber\UserSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
